# Generated by Django 4.1.3 on 2022-12-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuses',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='statuses',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation date'),
        ),
    ]
